Adding back network attachments with proper peering
Sage-Bionetworks/iAtlas-infra pull request #9
Opened 2020-07-21 22:16 UTC by ahayden

We had removed the VPC peering at an earlier stage. This adds the stacks back and uses the proper values for making a peering request to admincentral.

2020-07-21 22:33 UTC, zaro0508 requested changes

2020-07-21 22:33 UTC, zaro0508 commented on config/common/peer-vpn-iatlasvpc.yaml
> +  VpcPrivateRouteTable: rtb-03749e8c822352561
the VpcPrivateRouteTable for iatlasvpc is `rtb-073c34d41ecd890b1` 

please double check these values

2020-07-22 15:32 UTC, zaro0508 requested changes

2020-07-22 18:05 UTC, ahayden commented on config/common/peer-vpn-iatlasvpc.yaml
> +  VpcPrivateRouteTable: rtb-073c34d41ecd890b1
Good idea

2020-07-22 18:29 UTC, zaro0508 approved these changes

2020-07-23 15:49 UTC, merged